### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Battjmo** [Battjmo/GrailedClone#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by Battjmo** [comment]
It's all ready to go on there whenever you have a minute. Thanks!

**Comment by andywynkoop** [comment]
Hey Nick!
Nice job so far, here are a few changes i'd like you to make:
- [ ] Logo should be . clickable link that routes to the homepage `/` (also: `cursor: pointer`)
- [ ] If I type in a bunch of gobbledygook as the route, `resaled.herokuapp.com/#/hdlewlhhbafbkewbrlfa`, I should get redirected to the homepage Route `/`
- [ ] Errors should go away when I click out of the modal or switch between sign up 

I like the demo username

**Comment by Battjmo** [comment]
Thanks, 2/3 done. Should I push to heroku again when I'm done or let you know or what's the procedure? I'm a little lost on how to do the redirect one as well.

**Comment by Battjmo** [comment]
Oh geez, just push it to heroku and now it's totally broken.
