### ISSUE TITLE
PA Review: Listings

### ISSUE THREAD

**Issue by Battjmo** [Battjmo/GrailedClone#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by Battjmo** [comment]
I seem to have hit a wall displaying the index page, they keep coming back undefined for reasons I have not yet successfully divined.

**Comment by Battjmo** [comment]
Alright, it shows things for reasons I don't entirely understand owwww!

**Comment by Battjmo** [comment]
Questions so far:

1. When I try and access my listing form in editing mode, it doens't pass through the user_id from the listing for reasons I have not been able to comprehend.

2. On a similar note: I want to display info about a listing's user in its show page, but am having trouble getting that info to flow through to the page as well.

3. When I create a listing, it doesn't show up in the main feed until I refresh the page.

4. I set my list items to have keys based on their id numbers, which should all be unique, but I still get a unique key warning every time my index pages loads in the console.

**Comment by Battjmo** [comment]
Alright, this is pretty well done, ready for you to check it out. Are you coming in today? I'd love to have a chat.

**Comment by andywynkoop** [comment]
Yep I'm here. I'll look it over now if you're ready. Also we can have a meeting some time this morning too if you want!

**Comment by Battjmo** [comment]
Cool, I'm into either order. Just throwing more seeds on now so you can see the flex flex.

**Comment by Battjmo** [comment]
Thanks, the edit page has been a nightmare. Debating whether to move on or spend more time on it, the rest of the corrections are pretty easy. 

One thing: are you manually navigating to the edit page for the listing you didn't make? I made the button not show up unless you made the listing.

**Comment by Battjmo** [comment]
Also yes, I'd love to meet up and talk strategy at some point. The listings have taken way longer than I meant them too and I'm not sure how I should triage the rest of the stuff I have to do.

**Comment by Battjmo** [comment]
The editing error thing is an activestorage error that Liz and I attacked for more than an hour yesterday with no success. That's why I put in the must add image label on there, the photos cause all kinds of issues with editing. It's specifically that you have to change the image.

**Comment by Battjmo** [comment]
New version is up.

**Comment by Battjmo** [comment]
Just restyled the user link on the listing show page, not going to both to push again just for that yeah? suffice to say it looks fine now.

**Comment by andywynkoop** [comment]
- [ ] Give Images fixed width
- [ ] Change flex `justify-content` property to default and give list items fixed margin

**Comment by andywynkoop** [comment]
Hey Nick,
I think the listing index page looks good, but I think you still need to make a few changes to the styling on the listing show page. When viewed on a more narrow screen, the right side of the page gets hidden underneath the image. My suggestion would be to remove any percentage-based styling and instead use fixed pixels within the container (outside of this container is fine if you want it to always be centered or something).

**Comment by Battjmo** [comment]
Good call, done and done.
