### ISSUE TITLE
PA Review: User Profiles

### ISSUE THREAD

**Issue by Battjmo** [Battjmo/GrailedClone#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by Battjmo** [comment]
Got this all squared away! Went a lot faster than the last MVP, thankfully.

**Comment by andywynkoop** [comment]
- [ ] Measurements field should show ' No measurements' when empty (Roger Daltrey currently is 0' 0" and null lbs)
- [ ] Even though its currently the only link on the page, 'Listings' should be underlined and clickable (`cursor: pointer`) to match the styling on grailed
- [ ] Same thing with the username display - Even if you don't have all of those features yet, it might be nice to have some default values in there to make it appear more complete (default photo, default star rating, etc.)
- [ ] Sizes and prices should also be the same size as the other listing text (also for index)

**Comment by Battjmo** [comment]
Okay, switching back to this now. 

One other question, in terms of matching grailed: their search bar is in the header and can be used on any page, but used to be on the index page. Can I do it the latter way? the header way seems substantially harder and time is short.

Thanks.

**Comment by Battjmo** [comment]
Alright, got those dusted off. My stars aren't quite the same as railed but I rather like them, could I leave them as is?

**Comment by Battjmo** [comment]
These should be all ready to go when you get a chance.

Thanks so much for all your help with this. You have been and are awesome.

**Comment by andywynkoop** [comment]
Thanks you too!
